export const {
  EXPO_ANDROID_ID,
  EXPO_PUBLIC_APPWRITE_ENDPOINT,
  EXPO_PUBLIC_APPWRITE_PROJECT_ID,
  EXPO_PUBLIC_APPWRITE_PROJECT_NAME,
  EXPO_PUBLIC_DATABASE_ID,
  EXPO_PUBLIC_TABLE_AGENTS_ID,
  EXPO_PUBLIC_TABLE_GALLERIES_ID,
  EXPO_PUBLIC_TABLE_PROPERTIES_ID,
  EXPO_PUBLIC_TABLE_REVIEWS_ID,
  NODE_ENV,
} = process.env;

// Fallback values for debugging
if (!EXPO_PUBLIC_DATABASE_ID) {
  console.warn("EXPO_PUBLIC_DATABASE_ID is not set in environment variables");
}
